[package]
name = "slowtec-web"
version = "0.0.1"
authors = [ "slowtec GmbH" ]
license = "MIT/Apache-2.0"
publish = false

[patch.crates-io]
slowtec-core = { path = "../slowtec-core" }

[dependencies]
slowtec-core = "*"
failure = "*"
futures = "0.1"
warp = "*"
